// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/composer/composer.proto

package composer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encoder       string                 `protobuf:"bytes,1,opt,name=Encoder,proto3" json:"Encoder,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	FFmpegVersion string                 `protobuf:"bytes,3,opt,name=FFmpegVersion,proto3" json:"FFmpegVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_composer_composer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_composer_composer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_composer_composer_proto_rawDescGZIP(), []int{0}
}

func (x *GetTaskRequest) GetEncoder() string {
	if x != nil {
		return x.Encoder
	}
	return ""
}

func (x *GetTaskRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetTaskRequest) GetFFmpegVersion() string {
	if x != nil {
		return x.FFmpegVersion
	}
	return ""
}

type FinishTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=Task,proto3" json:"Task,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=FinishedAt,proto3" json:"FinishedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishTaskRequest) Reset() {
	*x = FinishTaskRequest{}
	mi := &file_proto_composer_composer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTaskRequest) ProtoMessage() {}

func (x *FinishTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_composer_composer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTaskRequest.ProtoReflect.Descriptor instead.
func (*FinishTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_composer_composer_proto_rawDescGZIP(), []int{1}
}

func (x *FinishTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *FinishTaskRequest) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *FinishTaskRequest) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type UpdateProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            []byte                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`       // taskID
	Delta         *durationpb.Duration   `protobuf:"bytes,2,opt,name=Delta,proto3" json:"Delta,omitempty"` // how much was encoded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProgressRequest) Reset() {
	*x = UpdateProgressRequest{}
	mi := &file_proto_composer_composer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProgressRequest) ProtoMessage() {}

func (x *UpdateProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_composer_composer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProgressRequest.ProtoReflect.Descriptor instead.
func (*UpdateProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_composer_composer_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProgressRequest) GetID() []byte {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *UpdateProgressRequest) GetDelta() *durationpb.Duration {
	if x != nil {
		return x.Delta
	}
	return nil
}

// see https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_composer_composer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_composer_composer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_composer_composer_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Error) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Error) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_composer_composer_proto protoreflect.FileDescriptor

const file_proto_composer_composer_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/composer/composer.proto\x12\bcomposer\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x19proto/composer/task.proto\"l\n" +
	"\x0eGetTaskRequest\x12\x18\n" +
	"\aEncoder\x18\x01 \x01(\tR\aEncoder\x12\x1a\n" +
	"\bHostname\x18\x02 \x01(\tR\bHostname\x12$\n" +
	"\rFFmpegVersion\x18\x03 \x01(\tR\rFFmpegVersion\"\x9a\x01\n" +
	"\x11FinishTaskRequest\x12\"\n" +
	"\x04Task\x18\x01 \x01(\v2\x0e.composer.TaskR\x04Task\x12%\n" +
	"\x05Error\x18\x02 \x01(\v2\x0f.composer.ErrorR\x05Error\x12:\n" +
	"\n" +
	"FinishedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"FinishedAt\"X\n" +
	"\x15UpdateProgressRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\fR\x02ID\x12/\n" +
	"\x05Delta\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x05Delta\"\xaf\x01\n" +
	"\x05Error\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x129\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1d.composer.Error.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xcd\x01\n" +
	"\bComposer\x123\n" +
	"\aGetTask\x12\x18.composer.GetTaskRequest\x1a\x0e.composer.Task\x12A\n" +
	"\n" +
	"FinishTask\x12\x1b.composer.FinishTaskRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x0eUpdateProgress\x12\x1f.composer.UpdateProgressRequest\x1a\x16.google.protobuf.EmptyB0Z.github.com/timohahaa/transcoder/proto/composerb\x06proto3"

var (
	file_proto_composer_composer_proto_rawDescOnce sync.Once
	file_proto_composer_composer_proto_rawDescData []byte
)

func file_proto_composer_composer_proto_rawDescGZIP() []byte {
	file_proto_composer_composer_proto_rawDescOnce.Do(func() {
		file_proto_composer_composer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_composer_composer_proto_rawDesc), len(file_proto_composer_composer_proto_rawDesc)))
	})
	return file_proto_composer_composer_proto_rawDescData
}

var file_proto_composer_composer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_composer_composer_proto_goTypes = []any{
	(*GetTaskRequest)(nil),        // 0: composer.GetTaskRequest
	(*FinishTaskRequest)(nil),     // 1: composer.FinishTaskRequest
	(*UpdateProgressRequest)(nil), // 2: composer.UpdateProgressRequest
	(*Error)(nil),                 // 3: composer.Error
	nil,                           // 4: composer.Error.MetadataEntry
	(*Task)(nil),                  // 5: composer.Task
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 7: google.protobuf.Duration
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_proto_composer_composer_proto_depIdxs = []int32{
	5, // 0: composer.FinishTaskRequest.Task:type_name -> composer.Task
	3, // 1: composer.FinishTaskRequest.Error:type_name -> composer.Error
	6, // 2: composer.FinishTaskRequest.FinishedAt:type_name -> google.protobuf.Timestamp
	7, // 3: composer.UpdateProgressRequest.Delta:type_name -> google.protobuf.Duration
	4, // 4: composer.Error.metadata:type_name -> composer.Error.MetadataEntry
	0, // 5: composer.Composer.GetTask:input_type -> composer.GetTaskRequest
	1, // 6: composer.Composer.FinishTask:input_type -> composer.FinishTaskRequest
	2, // 7: composer.Composer.UpdateProgress:input_type -> composer.UpdateProgressRequest
	5, // 8: composer.Composer.GetTask:output_type -> composer.Task
	8, // 9: composer.Composer.FinishTask:output_type -> google.protobuf.Empty
	8, // 10: composer.Composer.UpdateProgress:output_type -> google.protobuf.Empty
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_composer_composer_proto_init() }
func file_proto_composer_composer_proto_init() {
	if File_proto_composer_composer_proto != nil {
		return
	}
	file_proto_composer_task_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_composer_composer_proto_rawDesc), len(file_proto_composer_composer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_composer_composer_proto_goTypes,
		DependencyIndexes: file_proto_composer_composer_proto_depIdxs,
		MessageInfos:      file_proto_composer_composer_proto_msgTypes,
	}.Build()
	File_proto_composer_composer_proto = out.File
	file_proto_composer_composer_proto_goTypes = nil
	file_proto_composer_composer_proto_depIdxs = nil
}
