// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/composer/preset.proto

package composer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Preset struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Quality        string                 `protobuf:"bytes,1,opt,name=Quality,proto3" json:"Quality,omitempty"` // 360, 720, 1440, etc...
	MaxBitRate     int64                  `protobuf:"varint,2,opt,name=MaxBitRate,proto3" json:"MaxBitRate,omitempty"`
	MinBitRate     int64                  `protobuf:"varint,3,opt,name=MinBitRate,proto3" json:"MinBitRate,omitempty"`
	FPS            string                 `protobuf:"bytes,4,opt,name=FPS,proto3" json:"FPS,omitempty"`
	Codec          string                 `protobuf:"bytes,5,opt,name=Codec,proto3" json:"Codec,omitempty"`
	Bufsize        int64                  `protobuf:"varint,6,opt,name=Bufsize,proto3" json:"Bufsize,omitempty"`
	GOPSeconds     int32                  `protobuf:"varint,7,opt,name=GOPSeconds,proto3" json:"GOPSeconds,omitempty"`
	Profile        string                 `protobuf:"bytes,8,opt,name=Profile,proto3" json:"Profile,omitempty"`
	Level          string                 `protobuf:"bytes,9,opt,name=Level,proto3" json:"Level,omitempty"`
	CRF            int32                  `protobuf:"varint,10,opt,name=CRF,proto3" json:"CRF,omitempty"` // -cq for GPU and -crf for CPU
	ColorTrc       string                 `protobuf:"bytes,11,opt,name=ColorTrc,proto3" json:"ColorTrc,omitempty"`
	ColorSpace     string                 `protobuf:"bytes,12,opt,name=ColorSpace,proto3" json:"ColorSpace,omitempty"`
	ColorPrimaries string                 `protobuf:"bytes,13,opt,name=ColorPrimaries,proto3" json:"ColorPrimaries,omitempty"`
	Tune           string                 `protobuf:"bytes,14,opt,name=Tune,proto3" json:"Tune,omitempty"`           // psnr/ssim/grain/zerolatency/animation/film - content type
	Transpose      string                 `protobuf:"bytes,15,opt,name=Transpose,proto3" json:"Transpose,omitempty"` // clock/cclock/flip
	IsVertical     bool                   `protobuf:"varint,16,opt,name=IsVertical,proto3" json:"IsVertical,omitempty"`
	Width          int32                  `protobuf:"varint,17,opt,name=Width,proto3" json:"Width,omitempty"`
	Height         int32                  `protobuf:"varint,18,opt,name=Height,proto3" json:"Height,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Preset) Reset() {
	*x = Preset{}
	mi := &file_proto_composer_preset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preset) ProtoMessage() {}

func (x *Preset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_composer_preset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preset.ProtoReflect.Descriptor instead.
func (*Preset) Descriptor() ([]byte, []int) {
	return file_proto_composer_preset_proto_rawDescGZIP(), []int{0}
}

func (x *Preset) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *Preset) GetMaxBitRate() int64 {
	if x != nil {
		return x.MaxBitRate
	}
	return 0
}

func (x *Preset) GetMinBitRate() int64 {
	if x != nil {
		return x.MinBitRate
	}
	return 0
}

func (x *Preset) GetFPS() string {
	if x != nil {
		return x.FPS
	}
	return ""
}

func (x *Preset) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *Preset) GetBufsize() int64 {
	if x != nil {
		return x.Bufsize
	}
	return 0
}

func (x *Preset) GetGOPSeconds() int32 {
	if x != nil {
		return x.GOPSeconds
	}
	return 0
}

func (x *Preset) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *Preset) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Preset) GetCRF() int32 {
	if x != nil {
		return x.CRF
	}
	return 0
}

func (x *Preset) GetColorTrc() string {
	if x != nil {
		return x.ColorTrc
	}
	return ""
}

func (x *Preset) GetColorSpace() string {
	if x != nil {
		return x.ColorSpace
	}
	return ""
}

func (x *Preset) GetColorPrimaries() string {
	if x != nil {
		return x.ColorPrimaries
	}
	return ""
}

func (x *Preset) GetTune() string {
	if x != nil {
		return x.Tune
	}
	return ""
}

func (x *Preset) GetTranspose() string {
	if x != nil {
		return x.Transpose
	}
	return ""
}

func (x *Preset) GetIsVertical() bool {
	if x != nil {
		return x.IsVertical
	}
	return false
}

func (x *Preset) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Preset) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type AudioPreset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      int32                  `protobuf:"varint,1,opt,name=Channels,proto3" json:"Channels,omitempty"`
	Bitrate       int64                  `protobuf:"varint,2,opt,name=Bitrate,proto3" json:"Bitrate,omitempty"`
	SampleRate    int64                  `protobuf:"varint,3,opt,name=SampleRate,proto3" json:"SampleRate,omitempty"`
	PadBefore     float32                `protobuf:"fixed32,4,opt,name=PadBefore,proto3" json:"PadBefore,omitempty"`
	PadAfter      float32                `protobuf:"fixed32,5,opt,name=PadAfter,proto3" json:"PadAfter,omitempty"`
	TrimBefore    float32                `protobuf:"fixed32,6,opt,name=TrimBefore,proto3" json:"TrimBefore,omitempty"`
	TrimDuration  float32                `protobuf:"fixed32,7,opt,name=TrimDuration,proto3" json:"TrimDuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioPreset) Reset() {
	*x = AudioPreset{}
	mi := &file_proto_composer_preset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioPreset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioPreset) ProtoMessage() {}

func (x *AudioPreset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_composer_preset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioPreset.ProtoReflect.Descriptor instead.
func (*AudioPreset) Descriptor() ([]byte, []int) {
	return file_proto_composer_preset_proto_rawDescGZIP(), []int{1}
}

func (x *AudioPreset) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioPreset) GetBitrate() int64 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *AudioPreset) GetSampleRate() int64 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioPreset) GetPadBefore() float32 {
	if x != nil {
		return x.PadBefore
	}
	return 0
}

func (x *AudioPreset) GetPadAfter() float32 {
	if x != nil {
		return x.PadAfter
	}
	return 0
}

func (x *AudioPreset) GetTrimBefore() float32 {
	if x != nil {
		return x.TrimBefore
	}
	return 0
}

func (x *AudioPreset) GetTrimDuration() float32 {
	if x != nil {
		return x.TrimDuration
	}
	return 0
}

var File_proto_composer_preset_proto protoreflect.FileDescriptor

const file_proto_composer_preset_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/composer/preset.proto\x12\bcomposer\"\xea\x03\n" +
	"\x06Preset\x12\x18\n" +
	"\aQuality\x18\x01 \x01(\tR\aQuality\x12\x1e\n" +
	"\n" +
	"MaxBitRate\x18\x02 \x01(\x03R\n" +
	"MaxBitRate\x12\x1e\n" +
	"\n" +
	"MinBitRate\x18\x03 \x01(\x03R\n" +
	"MinBitRate\x12\x10\n" +
	"\x03FPS\x18\x04 \x01(\tR\x03FPS\x12\x14\n" +
	"\x05Codec\x18\x05 \x01(\tR\x05Codec\x12\x18\n" +
	"\aBufsize\x18\x06 \x01(\x03R\aBufsize\x12\x1e\n" +
	"\n" +
	"GOPSeconds\x18\a \x01(\x05R\n" +
	"GOPSeconds\x12\x18\n" +
	"\aProfile\x18\b \x01(\tR\aProfile\x12\x14\n" +
	"\x05Level\x18\t \x01(\tR\x05Level\x12\x10\n" +
	"\x03CRF\x18\n" +
	" \x01(\x05R\x03CRF\x12\x1a\n" +
	"\bColorTrc\x18\v \x01(\tR\bColorTrc\x12\x1e\n" +
	"\n" +
	"ColorSpace\x18\f \x01(\tR\n" +
	"ColorSpace\x12&\n" +
	"\x0eColorPrimaries\x18\r \x01(\tR\x0eColorPrimaries\x12\x12\n" +
	"\x04Tune\x18\x0e \x01(\tR\x04Tune\x12\x1c\n" +
	"\tTranspose\x18\x0f \x01(\tR\tTranspose\x12\x1e\n" +
	"\n" +
	"IsVertical\x18\x10 \x01(\bR\n" +
	"IsVertical\x12\x14\n" +
	"\x05Width\x18\x11 \x01(\x05R\x05Width\x12\x16\n" +
	"\x06Height\x18\x12 \x01(\x05R\x06Height\"\xe1\x01\n" +
	"\vAudioPreset\x12\x1a\n" +
	"\bChannels\x18\x01 \x01(\x05R\bChannels\x12\x18\n" +
	"\aBitrate\x18\x02 \x01(\x03R\aBitrate\x12\x1e\n" +
	"\n" +
	"SampleRate\x18\x03 \x01(\x03R\n" +
	"SampleRate\x12\x1c\n" +
	"\tPadBefore\x18\x04 \x01(\x02R\tPadBefore\x12\x1a\n" +
	"\bPadAfter\x18\x05 \x01(\x02R\bPadAfter\x12\x1e\n" +
	"\n" +
	"TrimBefore\x18\x06 \x01(\x02R\n" +
	"TrimBefore\x12\"\n" +
	"\fTrimDuration\x18\a \x01(\x02R\fTrimDurationB0Z.github.com/timohahaa/transcoder/proto/composerb\x06proto3"

var (
	file_proto_composer_preset_proto_rawDescOnce sync.Once
	file_proto_composer_preset_proto_rawDescData []byte
)

func file_proto_composer_preset_proto_rawDescGZIP() []byte {
	file_proto_composer_preset_proto_rawDescOnce.Do(func() {
		file_proto_composer_preset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_composer_preset_proto_rawDesc), len(file_proto_composer_preset_proto_rawDesc)))
	})
	return file_proto_composer_preset_proto_rawDescData
}

var file_proto_composer_preset_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_composer_preset_proto_goTypes = []any{
	(*Preset)(nil),      // 0: composer.Preset
	(*AudioPreset)(nil), // 1: composer.AudioPreset
}
var file_proto_composer_preset_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_composer_preset_proto_init() }
func file_proto_composer_preset_proto_init() {
	if File_proto_composer_preset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_composer_preset_proto_rawDesc), len(file_proto_composer_preset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_composer_preset_proto_goTypes,
		DependencyIndexes: file_proto_composer_preset_proto_depIdxs,
		MessageInfos:      file_proto_composer_preset_proto_msgTypes,
	}.Build()
	File_proto_composer_preset_proto = out.File
	file_proto_composer_preset_proto_goTypes = nil
	file_proto_composer_preset_proto_depIdxs = nil
}
