// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/composer/task.proto

package composer

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            []byte                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`      // taskID for a video-task
	Part          int32                  `protobuf:"varint,2,opt,name=Part,proto3" json:"Part,omitempty"` // chunk (subtask) number
	PartsTotal    int32                  `protobuf:"varint,3,opt,name=PartsTotal,proto3" json:"PartsTotal,omitempty"`
	Video         *Video                 `protobuf:"bytes,4,opt,name=Video,proto3" json:"Video,omitempty"`
	Audio         *Audio                 `protobuf:"bytes,5,opt,name=Audio,proto3" json:"Audio,omitempty"`
	Source        string                 `protobuf:"bytes,6,opt,name=Source,proto3" json:"Source,omitempty"` // url
	PushTo        string                 `protobuf:"bytes,7,opt,name=PushTo,proto3" json:"PushTo,omitempty"` // url
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Features      map[string]bool        `protobuf:"bytes,9,rep,name=Features,proto3" json:"Features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_composer_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_composer_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_composer_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetID() []byte {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *Task) GetPart() int32 {
	if x != nil {
		return x.Part
	}
	return 0
}

func (x *Task) GetPartsTotal() int32 {
	if x != nil {
		return x.PartsTotal
	}
	return 0
}

func (x *Task) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *Task) GetAudio() *Audio {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *Task) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Task) GetPushTo() string {
	if x != nil {
		return x.PushTo
	}
	return ""
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetFeatures() map[string]bool {
	if x != nil {
		return x.Features
	}
	return nil
}

type Audio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codec         string                 `protobuf:"bytes,1,opt,name=Codec,proto3" json:"Codec,omitempty"`
	BitRate       int64                  `protobuf:"varint,2,opt,name=BitRate,proto3" json:"BitRate,omitempty"`
	Duration      float32                `protobuf:"fixed32,3,opt,name=Duration,proto3" json:"Duration,omitempty"`
	TrackNum      int32                  `protobuf:"varint,4,opt,name=TrackNum,proto3" json:"TrackNum,omitempty"`
	Preset        *AudioPreset           `protobuf:"bytes,5,opt,name=Preset,proto3" json:"Preset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audio) Reset() {
	*x = Audio{}
	mi := &file_proto_composer_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audio) ProtoMessage() {}

func (x *Audio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_composer_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audio.ProtoReflect.Descriptor instead.
func (*Audio) Descriptor() ([]byte, []int) {
	return file_proto_composer_task_proto_rawDescGZIP(), []int{1}
}

func (x *Audio) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *Audio) GetBitRate() int64 {
	if x != nil {
		return x.BitRate
	}
	return 0
}

func (x *Audio) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Audio) GetTrackNum() int32 {
	if x != nil {
		return x.TrackNum
	}
	return 0
}

func (x *Audio) GetPreset() *AudioPreset {
	if x != nil {
		return x.Preset
	}
	return nil
}

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codec         string                 `protobuf:"bytes,1,opt,name=Codec,proto3" json:"Codec,omitempty"`
	BitRate       int64                  `protobuf:"varint,2,opt,name=BitRate,proto3" json:"BitRate,omitempty"`
	Duration      float32                `protobuf:"fixed32,3,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Quality       string                 `protobuf:"bytes,4,opt,name=Quality,proto3" json:"Quality,omitempty"`
	PixFmt        string                 `protobuf:"bytes,5,opt,name=PixFmt,proto3" json:"PixFmt,omitempty"`
	CreatePoster  bool                   `protobuf:"varint,6,opt,name=CreatePoster,proto3" json:"CreatePoster,omitempty"`
	Presets       []*Preset              `protobuf:"bytes,7,rep,name=Presets,proto3" json:"Presets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_proto_composer_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_proto_composer_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_proto_composer_task_proto_rawDescGZIP(), []int{2}
}

func (x *Video) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *Video) GetBitRate() int64 {
	if x != nil {
		return x.BitRate
	}
	return 0
}

func (x *Video) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Video) GetQuality() string {
	if x != nil {
		return x.Quality
	}
	return ""
}

func (x *Video) GetPixFmt() string {
	if x != nil {
		return x.PixFmt
	}
	return ""
}

func (x *Video) GetCreatePoster() bool {
	if x != nil {
		return x.CreatePoster
	}
	return false
}

func (x *Video) GetPresets() []*Preset {
	if x != nil {
		return x.Presets
	}
	return nil
}

var File_proto_composer_task_proto protoreflect.FileDescriptor

const file_proto_composer_task_proto_rawDesc = "" +
	"\n" +
	"\x19proto/composer/task.proto\x12\bcomposer\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bproto/composer/preset.proto\"\xf9\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\fR\x02ID\x12\x12\n" +
	"\x04Part\x18\x02 \x01(\x05R\x04Part\x12\x1e\n" +
	"\n" +
	"PartsTotal\x18\x03 \x01(\x05R\n" +
	"PartsTotal\x12%\n" +
	"\x05Video\x18\x04 \x01(\v2\x0f.composer.VideoR\x05Video\x12%\n" +
	"\x05Audio\x18\x05 \x01(\v2\x0f.composer.AudioR\x05Audio\x12\x16\n" +
	"\x06Source\x18\x06 \x01(\tR\x06Source\x12\x16\n" +
	"\x06PushTo\x18\a \x01(\tR\x06PushTo\x128\n" +
	"\tCreatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\bFeatures\x18\t \x03(\v2\x1c.composer.Task.FeaturesEntryR\bFeatures\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x9e\x01\n" +
	"\x05Audio\x12\x14\n" +
	"\x05Codec\x18\x01 \x01(\tR\x05Codec\x12\x18\n" +
	"\aBitRate\x18\x02 \x01(\x03R\aBitRate\x12\x1a\n" +
	"\bDuration\x18\x03 \x01(\x02R\bDuration\x12\x1a\n" +
	"\bTrackNum\x18\x04 \x01(\x05R\bTrackNum\x12-\n" +
	"\x06Preset\x18\x05 \x01(\v2\x15.composer.AudioPresetR\x06Preset\"\xd5\x01\n" +
	"\x05Video\x12\x14\n" +
	"\x05Codec\x18\x01 \x01(\tR\x05Codec\x12\x18\n" +
	"\aBitRate\x18\x02 \x01(\x03R\aBitRate\x12\x1a\n" +
	"\bDuration\x18\x03 \x01(\x02R\bDuration\x12\x18\n" +
	"\aQuality\x18\x04 \x01(\tR\aQuality\x12\x16\n" +
	"\x06PixFmt\x18\x05 \x01(\tR\x06PixFmt\x12\"\n" +
	"\fCreatePoster\x18\x06 \x01(\bR\fCreatePoster\x12*\n" +
	"\aPresets\x18\a \x03(\v2\x10.composer.PresetR\aPresetsB0Z.github.com/timohahaa/transcoder/proto/composerb\x06proto3"

var (
	file_proto_composer_task_proto_rawDescOnce sync.Once
	file_proto_composer_task_proto_rawDescData []byte
)

func file_proto_composer_task_proto_rawDescGZIP() []byte {
	file_proto_composer_task_proto_rawDescOnce.Do(func() {
		file_proto_composer_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_composer_task_proto_rawDesc), len(file_proto_composer_task_proto_rawDesc)))
	})
	return file_proto_composer_task_proto_rawDescData
}

var file_proto_composer_task_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_composer_task_proto_goTypes = []any{
	(*Task)(nil),                  // 0: composer.Task
	(*Audio)(nil),                 // 1: composer.Audio
	(*Video)(nil),                 // 2: composer.Video
	nil,                           // 3: composer.Task.FeaturesEntry
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*AudioPreset)(nil),           // 5: composer.AudioPreset
	(*Preset)(nil),                // 6: composer.Preset
}
var file_proto_composer_task_proto_depIdxs = []int32{
	2, // 0: composer.Task.Video:type_name -> composer.Video
	1, // 1: composer.Task.Audio:type_name -> composer.Audio
	4, // 2: composer.Task.CreatedAt:type_name -> google.protobuf.Timestamp
	3, // 3: composer.Task.Features:type_name -> composer.Task.FeaturesEntry
	5, // 4: composer.Audio.Preset:type_name -> composer.AudioPreset
	6, // 5: composer.Video.Presets:type_name -> composer.Preset
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_composer_task_proto_init() }
func file_proto_composer_task_proto_init() {
	if File_proto_composer_task_proto != nil {
		return
	}
	file_proto_composer_preset_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_composer_task_proto_rawDesc), len(file_proto_composer_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_composer_task_proto_goTypes,
		DependencyIndexes: file_proto_composer_task_proto_depIdxs,
		MessageInfos:      file_proto_composer_task_proto_msgTypes,
	}.Build()
	File_proto_composer_task_proto = out.File
	file_proto_composer_task_proto_goTypes = nil
	file_proto_composer_task_proto_depIdxs = nil
}
